import type { Project } from '@/types';

export const projects: Project[] = [
  {
    id: 1,
    title: 'DNA Partners - Business Advisory Website',
    description: 'A professional website for experienced entrepreneurs advising leaders of growth companies.',
    category: 'Web Development',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    tags: ['Next.js', 'React', 'TypeScript'],
    image: '/website2.png',
    video: '/vid2.mp4',
    rating: 5,
    href: '/projects/api-integration-service',
  },
  {
    id: 2,
    title: 'Burnt Blue Holdings - Investment Platform',
    description: 'A sophisticated investment platform for bourbon wholesale trading and alternative investment opportunities.',
    category: 'Web Development',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS'],
    tags: ['Next.js', 'React', 'TypeScript'],
    image: '/fullweb7.webp',
    video: '/vid1.mp4',
    rating: 5,
    href: '/projects/burnt-blue-holdings',
  },
  {
    id: 3,
    title: 'iSplit - Smart Expense Tracker',
    description: 'A comprehensive expense tracking and bill splitting app with AI-powered insights and group management features.',
    category: 'Web Development',
    technologies: ['React', 'JavaScript', 'Node.js', 'Express'],
    tags: ['React', 'JavaScript', 'Node.js'],
    image: '/fullweb8.png',
    video: '/vid2.mp4',
    rating: 5,
    href: '/projects/isplit-expense-tracker',
  },
  {
    id: 4,
    title: 'License Plate Designer - Visual Configurator',
    description: 'An advanced license plate design configurator with visual editor, template system, and high-resolution export capabilities.',
    category: 'Web Development',
    technologies: ['React', 'Next.js', 'TypeScript', 'Canvas API'],
    tags: ['React', 'Next.js', 'TypeScript'],
    image: '/website3.png',
    video: '/vid1.mp4',
    rating: 5,
    href: '/projects/license-plate-designer',
  },
]